taste_of_stockholm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('todo.urls')),
    path('accounts/', include('allauth.urls')),
]

todo/urls.py
from . import views
from django.urls import path


app_name = 'todo'

urlpatterns = [
    path('', views.PostList.as_view(), name="index,"),
    path('ag/', views.ag, name="ag"),
    path('spesso/', views.ag, name="spesso"),
    path('sushisho/', views.ag, name="sushisho"),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "DRAFT"), (1, "PUBLISHED"))

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    exerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='blogpost_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"comment {self.body} by {self.name}"
    



           

todo/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post




class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 6


def index(request):
    return render(request, 'index.html', {})


def ag(request):
    return render(request, 'ag.html', {})


def spesso(request):
    return render(request, 'spesso.html', {})

templates/Pages/login.html
{% extends "base.html" %}

{% block content %}

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Register</div>
                    <div class="card-body">
                        <form action="" method="">
                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>
                                <div class="col-md-6">
                                    <input type="text" id="email_address" class="form-control" name="email-address" required autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                <div class="col-md-6">
                                    <input type="password" id="password" class="form-control" name="password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember"> Remember Me
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

</main>

templates/ag.html
{% extends "base.html" %}

{% block content %}

<h1>test</h1>

<div class="container-fluid">
    <div class="row">

        <!-- Blog entries Column-->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <p class="author">Author: {{ post.author }}</p>

                    </div>
                </div>
            </div>
            <a href="#" class="post-link">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.excerpt }}</p>
            </a>
            <hr />
            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
               {{ post.number_of_likes }}</p>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
            {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}
            
        </div>
    </div>
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>Taste of Stockholm</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
</head>

<body>

    <nav id="navmeny" class="navbar navbar-expand-lg navbar-black bg-dark">
      <div class="container-fluid">
        <div class="navbar-header">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          <a class="navbar-brand" href="#">Taste of Stockholm</a>
        </div>
        <div class="navbar" id="myNavbar" class="nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#" style ="text-decoration: none;">Home</a>
            </li>
            <li class="active"><a href="#" style ="text-decoration: none;">About</a>
            </li>
            <li class="active"><a href="{% url 'account_signup' %}" style ="text-decoration: none;">Register</a>
            </li>
            <li class="active"><a href="{% url 'account_login' %}" style ="text-decoration: none;">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    

    {% block content %}
    {% endblock content %}

    <footer id="footer" class="container-fluid text-center">
      <p>Footer Text</p>
    </footer>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
  
<body>
<div id="headline">
  <h1 class="headline-landingpage">Experience a taste journey in Stockholm</h1>
  <div class="py-5">
    <div class="container">
      <div class="row hidden-md-up">
        <div class="col-md-4">
          <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="../static/css/images/res-AG.png" alt="Card image cap">
            <div class="card-block">
              <h4 class="card-title">Resturang AG</h4>
              <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
              <a href="{% url 'todo:ag' %}" class="btn btn-primary">Click Here</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="../static/css/images/Spesso.png" alt="Card image cap">
            <div class="card-block">
              <h4 class="card-title">Spesso</h4>
              <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
              <a href="{% url 'todo:spesso' %}" class="btn btn-primary">Click Here</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="../static/css/images/sushi sho.png" alt="Card image cap">
            <div class="card-block">
              <h4 class="card-title">Sushi Sho</h4>
              <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
              <a href="{% url 'todo:sushisho' %}" class="btn btn-primary">Click Here</a>
            </div>
          </div>
        </div>
      </div><br>
    </div>    
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
</body>

{% endblock content %}

 

templates/spesso.html
{% extends "base.html" %}

{% block content %}
  

<div class="container-fluid">
    <div class="row">

        <!-- Blog entries Column-->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <p class="author">Author: {{ post.author }}</p>

                    </div>
                </div>
            </div>
            <a href="#" class="post-link">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.excerpt }}</p>
            </a>
            <hr />
            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
               {{ post.number_of_likes }}</p>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
            {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}
            
        </div>
    </div>
</div>

templates/sushisho.html
{% extends "base.html" %}

{% block content %}
  

<div class="container-fluid">
    <div class="row">

        <!-- Blog entries Column-->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <p class="author">Author: {{ post.author }}</p>

                    </div>
                </div>
            </div>
            <a href="#" class="post-link">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.excerpt }}</p>
            </a>
            <hr />
            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
               {{ post.number_of_likes }}</p>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
            {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}
            
        </div>
    </div>
</div>